import type { Genre, Venue, ConcertEvent, Filters } from "./types"

export const GENRE_LABELS: Record<Genre, string> = {
  rock: "Рок",
  pop: "Поп",
  electronic: "Электроника",
  jazz: "Джаз",
  classical: "Классика",
  "hip-hop": "Хип-хоп",
  metal: "Метал",
  folk: "Фолк",
  other: "Другое",
}

export const ALL_GENRES: Genre[] = Object.keys(GENRE_LABELS) as Genre[]

export const GENRE_COLORS: Record<Genre, string> = {
  rock: "bg-red-500/80 text-white",
  pop: "bg-pink-500/80 text-white",
  electronic: "bg-cyan-500/80 text-white",
  jazz: "bg-amber-500/80 text-white",
  classical: "bg-emerald-500/80 text-white",
  "hip-hop": "bg-orange-500/80 text-white",
  metal: "bg-zinc-500/80 text-white",
  folk: "bg-lime-600/80 text-white",
  other: "bg-slate-500/80 text-white",
}

export const MAP_CONFIG = {
  center: [37.6203, 55.7539] as [number, number], // Moscow center (Red Square area)
  zoom: 9.5,
  style: "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
}

export const ADMIN_PASSWORD = "admin"

export const DEFAULT_FILTERS: Filters = {
  genres: [],
  query: "",
}

export const getTodayISO = (): string => {
  const now = new Date()
  const year = now.getFullYear()
  const month = String(now.getMonth() + 1).padStart(2, "0")
  const day = String(now.getDate()).padStart(2, "0")
  return `${year}-${month}-${day}`
}

export const SEED_VENUES: Venue[] = [
  {
    id: "v1",
    name: "Crocus City Hall",
    address: "65-66 км МКАД, Красногорск",
    latitude: 55.8234,
    longitude: 37.3859,
    capacity: 7200,
    description: "Крупнейшая концертная площадка Москвы",
  },
  {
    id: "v2",
    name: "Adrenaline Stadium",
    address: "ул. Автозаводская, 23А",
    latitude: 55.7049,
    longitude: 37.6486,
    capacity: 8000,
    description: "Современная площадка для масштабных шоу",
  },
  {
    id: "v3",
    name: "ВТБ Арена",
    address: "Ленинградский просп., 36, стр. 33",
    latitude: 55.7917,
    longitude: 37.5617,
    capacity: 15000,
    description: "Многофункциональная арена",
  },
  {
    id: "v4",
    name: "Лужники",
    address: "ул. Лужники, 24",
    latitude: 55.7155,
    longitude: 37.5539,
    capacity: 81000,
    description: "Главный стадион страны",
  },
  {
    id: "v5",
    name: "Мегаспорт",
    address: "Ходынский бул., 3",
    latitude: 55.7775,
    longitude: 37.5308,
    capacity: 14000,
    description: "Дворец спорта с отличной акустикой",
  },
  {
    id: "v6",
    name: "Известия Hall",
    address: "Пушкинская пл., 5",
    latitude: 55.7652,
    longitude: 37.6072,
    capacity: 1500,
    description: "Камерный зал в центре Москвы",
  },
  {
    id: "v7",
    name: "Главclub Green Concert",
    address: "ул. Орджоникидзе, 11",
    latitude: 55.705,
    longitude: 37.6127,
    capacity: 3000,
    description: "Площадка для инди и альтернативной музыки",
  },
  {
    id: "v8",
    name: "Music Media Dome",
    address: "ш. Энтузиастов, 2",
    latitude: 55.7531,
    longitude: 37.699,
    capacity: 5000,
    description: "Купольная площадка с панорамным звуком",
  },
  {
    id: "v9",
    name: "16 Тонн",
    address: "Пресненский Вал, 6, стр. 1",
    latitude: 55.762,
    longitude: 37.573,
    capacity: 700,
    description: "Легендарный рок-клуб Москвы",
  },
  {
    id: "v10",
    name: "Концертный зал Зарядье",
    address: "ул. Варварка, 6, стр. 3",
    latitude: 55.751,
    longitude: 37.6275,
    capacity: 1600,
    description: "Современный филармонический зал",
  },
]

export const SEED_EVENTS: ConcertEvent[] = [
  {
    id: "e1",
    venueId: "v1",
    title: "Рок-фестиваль Москва 2026",
    artist: "Сборный концерт",
    genre: "rock",
    date: "2026-03-15",
    time: "19:00",
    price: 3500,
    priceMax: 8000,
    description: "Крупнейший рок-фестиваль столицы",
  },
  {
    id: "e2",
    venueId: "v6",
    title: "Джазовый вечер",
    artist: "Igor Butman Quartet",
    genre: "jazz",
    date: "2026-03-10",
    time: "20:00",
    price: 2000,
    priceMax: 5000,
    description: "Вечер классического джаза",
  },
  {
    id: "e3",
    venueId: "v2",
    title: "Electronic Wave",
    artist: "Deadmau5",
    genre: "electronic",
    date: "2026-03-22",
    time: "22:00",
    price: 4000,
    priceMax: 12000,
    description: "Масштабное электронное шоу",
  },
  {
    id: "e4",
    venueId: "v9",
    title: "Рок в подвале",
    artist: "Порнофильмы",
    genre: "rock",
    date: "2026-03-08",
    time: "20:00",
    price: 1500,
    description: "Панк-рок вечеринка",
  },
  {
    id: "e5",
    venueId: "v10",
    title: "Симфония весны",
    artist: "Московский филармонический оркестр",
    genre: "classical",
    date: "2026-03-20",
    time: "19:30",
    price: 2500,
    priceMax: 7000,
    description: "Весенний классический концерт",
  },
  {
    id: "e6",
    venueId: "v7",
    title: "Инди-фест",
    artist: "Мумий Тролль",
    genre: "pop",
    date: "2026-04-01",
    time: "20:00",
    price: 2000,
    priceMax: 4500,
    description: "Вечер лучших инди-хитов",
  },
  {
    id: "e7",
    venueId: "v5",
    title: "Hip-Hop Summit",
    artist: "Oxxxymiron",
    genre: "hip-hop",
    date: "2026-04-05",
    time: "21:00",
    price: 3000,
    priceMax: 10000,
    description: "Главное хип-хоп событие года",
  },
  {
    id: "e8",
    venueId: "v8",
    title: "Metal Night",
    artist: "Слот",
    genre: "metal",
    date: "2026-03-28",
    time: "19:00",
    price: 2500,
    priceMax: 5000,
    description: "Ночь тяжёлой музыки",
  },
  {
    id: "e9",
    venueId: "v2",
    title: "Electronic Night",
    artist: "Nina Kraviz",
    genre: "electronic",
    date: "2026-03-10",
    time: "22:00",
    price: 3000,
    priceMax: 7000,
    description: "Ночной сет от королевы техно",
  },
  {
    id: "e10",
    venueId: "v9",
    title: "Acoustic Evening",
    artist: "The Hatters",
    genre: "rock",
    date: "2026-03-11",
    time: "20:00",
    price: 2500,
    priceMax: 4500,
    description: "Акустический концерт в уютной обстановке",
  },
  {
    id: "e11",
    venueId: "v6",
    title: "Pop Star Night",
    artist: "Zivert",
    genre: "pop",
    date: "2026-03-11",
    time: "19:00",
    price: 3000,
    priceMax: 15000,
    description: "Большое сольное шоу",
  },
  {
    id: "e12",
    venueId: "v1",
    title: "Techno Rave",
    artist: "Charlotte de Witte",
    genre: "electronic",
    date: "2026-03-12",
    time: "23:00",
    price: 3500,
    priceMax: 8000,
    description: "Главное техно-событие весны",
  },
  {
    id: "e13",
    venueId: "v6",
    title: "City Jazz Session",
    artist: "Moscow Jazz Lab",
    genre: "jazz",
    date: "2026-03-12",
    time: "20:30",
    price: 1800,
    priceMax: 4200,
    description: "Камерный джазовый сет в центре",
  },
  {
    id: "e14",
    venueId: "v10",
    title: "Ночной органный час",
    artist: "Ансамбль Зарядье",
    genre: "classical",
    date: "2026-03-12",
    time: "21:15",
    price: 2000,
    priceMax: 5200,
    description: "Короткий ночной концерт в зале Зарядье",
  },
  {
    id: "e15",
    venueId: "v6",
    title: "Центр. Акустика",
    artist: "Квартет на Тверской",
    genre: "folk",
    date: "2026-03-13",
    time: "19:30",
    price: 1200,
    priceMax: 2600,
    description: "Тёплый акустический сет в центре",
  },
  {
    id: "e16",
    venueId: "v10",
    title: "Вечер в Зарядье",
    artist: "Solo Cello",
    genre: "classical",
    date: "2026-03-13",
    time: "20:00",
    price: 1800,
    priceMax: 3600,
    description: "Камерный вечер в самом центре",
  },
]
